<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name = "box_length" value = "0.6"></xacro:property>
    <xacro:property name = "box_width" value = "0.4"></xacro:property>
    <xacro:property name = "box_height" value = "0.2"></xacro:property>
    <xacro:property name = "wheel_radius" value = "0.1"></xacro:property>  
    <xacro:property name = "wheel_length" value = "0.05"></xacro:property>
    <xacro:property name = "caster_radius" value = "${wheel_radius / 2.0}"></xacro:property>  

    <link name = "base_link">
        <visual>
            <geometry>
                <box size = "${box_length} ${box_width} ${box_height}"/>
            </geometry>
            <origin xyz = "0 0 ${box_height}" rpy = "0 0 0"/>
            <material name ="red"/>
        </visual>
    </link>

    <xacro:macro name = "wheel_link" params = "prefix">
    <link name = "${prefix}_link">
        <visual>
            <geometry>
                <cylinder radius = "${wheel_radius}" length = "${wheel_length}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name ="blue"/>
        </visual>
    </link>
    </xacro:macro>
    <xacro:wheel_link prefix = "rw"/>
    <xacro:wheel_link prefix = "lw"/>

    <link name = "caster_link">
        <visual>
            <geometry>
                <sphere radius = "${caster_radius}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name ="blue"/>
        </visual>
    </link>

    <joint name = "base_rl_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "lw_link"/>
        <origin xyz = "-${box_length / 3.0} ${(box_width / 2.0) + (wheel_length / 2.0)} ${box_height / 2.0}" rpy = "${pi/2} 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>

    <joint name = "base_rr_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "rw_link"/>
        <origin xyz = "-${box_length / 3.0} -${(box_width / 2.0) + (wheel_length / 2.0)} ${box_height / 2.0}" rpy = "${pi/2} 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>

    <joint name = "base_caster_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "caster_link"/>
        <origin xyz = "${box_length / 3.0} 0 ${box_height / 4.0}" rpy = "${pi/2} 0 0"/>
        <axis xyz = "1 1 1"/>
    </joint>

</robot>