moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_shoulder_joint
      - shoulder_arm1_joint
      - arm1_arm2_joint
      - arm2_arm3_joint
      - arm3_gripper_base_joint

  gripper_controller:
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: True
   joints:
     - gripper_base_left_joint
     - gripper_base_right_joint
